### ISSUE TITLE
Primary navigation two variants for global search

### ISSUE THREAD

**Issue by adamsilver** [hmcts/design-system-backlog#30]
We already have a [primary navigation](http://hmcts-design-system.herokuapp.com/components/primary-navigation) component in the design system. We need to add a variant that can take two search form variants:

## (1) Inline search

![image](https://user-images.githubusercontent.com/37163/46787267-18523d80-cd2f-11e8-9397-44073c7d196a.png)

Mobile: 
![image](https://user-images.githubusercontent.com/37163/46787398-61a28d00-cd2f-11e8-8992-05aa89cf6b8c.png)

## (2) Expandable search (closed and open)

![image](https://user-images.githubusercontent.com/37163/46787294-2738f000-cd2f-11e8-9a09-f0b0bf4edd33.png)

Mobile:
![image](https://user-images.githubusercontent.com/37163/46787422-6f581280-cd2f-11e8-9fdf-0b9658f25c9d.png)

**Comment by blowfishsoup** [comment]
Is there a way we could distinguish visually between the header and the navigation bar perhaps?
![header and global navigation example](https://user-images.githubusercontent.com/6122620/43566406-2c653a06-9626-11e8-883d-548f40131699.png)

**Comment by PamelaWoods** [comment]
Update design to reflect the right place for the CASE-LEVEL Action Buttons
