### ISSUE TITLE
Currency input

### ISSUE THREAD

**Issue by robarmes** [hmcts/design-system-backlog#32]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/36768467/45151824-463fe180-b1c7-11e8-903c-2e8c3530cf68.gif)

**Comment by robarmes** [comment]
**When to use this component**
Use the Currency input component whenever you need users to tell you an amount of money in a particular currency, for example pounds sterling or euros. 

**How it works**
The Currency input component shows users which unit of currency they need to enter their amount in. (there is some hidden, screen-reader friendly label text on those inputs, for example “Enter amount in £”.)

Preventing non-numeric characters
The component uses input type=”text” rather than type=number to ensure that all users can enter the decimal symbol.

The Currency input component has a progressive enhancement that prevents non-numeric input. To use this enhancement, install the numeric input component or include `numeric-input.js` on the page and include the attribute `data-non-numeric` on the input.

**Research on this component**
This component has been tested in prototypes of several payment products with complete success.

**Comment by robarmes** [comment]
See example in one of our payment prototypes:
https://fee-register-prototype.herokuapp.com/currency-input

**Comment by adamsilver** [comment]
https://govuk-currency-input.herokuapp.com/
https://github.com/hannalaakso/accessible-currency-input

Good one ^

**Comment by adamsilver** [comment]
I've created something for us to review on Wednesday.
http://hmcts-frontend.herokuapp.com/components/currency-input

**Comment by PeteWilliams** [comment]
One thing to consider is alignment. Traditionally in things like Excel or anything tabular, numeric/currency input is right-aligned so decimal places line up, tens line up with tens, hundreds line up with hundreds etc. Makes comparisons and any mental arithmetic easier.

This is less important when the input is used on it's own, but potentially more important when entering a whole bunch of numbers (which we do in a couple places in CMC - [example](https://hmcts-cmc-prototype.herokuapp.com/prototypes/prototype-mar-2019/claimant/task-list/claim-amount-alt)). Could consider always right-aligning, or having a secondary class to right-align when used in tables/groups.

Also in the CMC version, the currency prefix is styled differently:
![image](https://user-images.githubusercontent.com/1325606/53968552-33af5200-40ef-11e9-902a-da6557f041af.png)
I wasn't involved with the design/testing of this, but I suspect it's to make it clear that it's not editable - you could argue in your design that it being just black text inside a textbox visually implies that it is an editable part of the field's value.

**Comment by adamsilver** [comment]
Thanks @PeteWilliams. I've updated it based on your crit:

![image](https://user-images.githubusercontent.com/37163/54014891-f9d55e80-4175-11e9-9263-ac48c581e97f.png)

**Comment by adamsilver** [comment]
Going to use a text input with number pattern as explained here:
https://adamsilver.io/articles/form-design-when-to-use-the-number-input/

**Comment by adamsilver** [comment]
Ready for review/approval: http://hmcts-design-system.herokuapp.com/components/currency-input

**Comment by PeteWilliams** [comment]
Have reviewed/approved this. And also to note, this pattern has already been successfully tested in CMC. 
Is there a label to add when something is approved, or do we just remove the 'in progress' one?

**Comment by adamsilver** [comment]
We just remove it. Thanks, Pete. All done.
