### ISSUE TITLE
Summary/details view patten

### ISSUE THREAD

**Issue by robarmes** [hmcts/design-system-backlog#33]
Desktop credit payment
<img width="538" alt="screen shot 2018-09-06 at 14 28 22" src="https://user-images.githubusercontent.com/36768467/45160455-68465d80-b1e1-11e8-94ce-7179fab610f7.png">

Desktop card payment
<img width="541" alt="screen shot 2018-09-06 at 14 28 33" src="https://user-images.githubusercontent.com/36768467/45160460-6c727b00-b1e1-11e8-90eb-0468fa8839ed.png">

Mobile credit payment
![screen shot 2018-09-06 at 14 38 16](https://user-images.githubusercontent.com/36768467/45160945-9e381180-b1e2-11e8-9ddd-77ab1d9396ca.png)

Mobile card payment
![screen shot 2018-09-06 at 14 37 50](https://user-images.githubusercontent.com/36768467/45160940-9aa48a80-b1e2-11e8-9a57-ecc6efccb153.png)

**Comment by robarmes** [comment]
**When to use this component**
Use the payment summary component whenever you need to display the details of a payment transaction which is for a fee.

The summary shows:

- Payment reference (generated by payhub) and amount paid

- Details of the fee the payment is covering

- Details of the payment method used

- Details of the payment status and it's history

**How it works**
Built as a reusable web component, install instructions here:
https://www.npmjs.com/package/@hmcts/ccpay-web-component

Each individual part of the payment summary are also available as separate components

** Responsive design version still to be built

**Research on this component**
This component has been tested in prototypes of several payment products.

**Comment by PamelaWoods** [comment]
Add a page to PATTERNS.  Needs to be named properly - review with Liz Jordan.
This is a copy of Check Your Answers to replay information back to people.

**Comment by adamsilver** [comment]
This is now in the GOV.UK Design System:
https://design-system.service.gov.uk/components/summary-list/
