### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by PamelaWoods** [hmcts/design-system-backlog#34]
@trevorsaint - please update the Alerts section on the HMCTS Pattern Library as discussed in Design Crit on 29 August.  
- Break out Alerts into Confirmation of tasks (in page) and Confirmation Page.
- Create a warning section & add warning alert there.
- Remove information alert and look at introducing an 'Add new comment' button to JUI.  (This may now be out of date given changes to Annotation).

**Comment by adamsilver** [comment]
The Confirmation Page pattern is in the GOV.UK Design System
https://design-system.service.gov.uk/patterns/confirmation-pages/
