### ISSUE TITLE
Common button text

### ISSUE THREAD

**Issue by FranW1** [hmcts/design-system-backlog#37]
Hello,
We have some common button text to add to the library:

Submit | Used at the end of the application to submit the data when all fields are complete.
Add another | Used to add another item.
Pay | Used to make a payment on the confirmation page from GOV.UK.
Sign in | Used to sign in to an account that has already been set up.
Sign out | Used to sign out of account.
Start | Used at the start of the service. Should only be used once in an end-to-end service.

This will be added to when more buttons are agreed.

Thanks!

**Comment by adamsilver** [comment]
I mentioned this to the GOV.UK Design System team and we agreed this should be added to their Button component page guidance.

HMRC identified the same need as us.

**Comment by danielculpan03** [comment]
Thanks for investigating this @adamsilver. What are the next steps (I'm thinking specifically from a content perspective - is there someone I need to liaise with)?

**Comment by adamsilver** [comment]
@danielculpan03 that would be amazing. Could you link up with @stevenaproctor from HMRC?

**Comment by adamsilver** [comment]
@danielculpan03 — could you liase with @stevenaproctor who's going to work on this (he works at HMRC).

**Comment by ghost** [comment]
@danielculpan03 Hi...both @jennifer-hodgson and I are looking at this from HMRC's point of view. This is our issue https://github.com/hmrc/design-patterns/issues/147 that covers similar things.

We were thinking of adding some content to https://design-system.service.gov.uk/components/button/ to cover what we both need. Does that sound OK?

**Comment by danielculpan03** [comment]
Hi @stevenaproctor - sure. If you could let me know what you finally decide, that would be great.

Aside from the suggestions above, we'll also have additional button text to add once it's agreed among the teams here, so would be good to make sure we're consistent. Thanks!

**Comment by adamsilver** [comment]
Can we close this one now @danielculpan03 given the new guidance in the design system?

**Comment by danielculpan03** [comment]
@adamsilver - sure
