### ISSUE TITLE
Global action buttons variant when too many to fit

### ISSUE THREAD

**Issue by PamelaWoods** [hmcts/design-system-backlog#39]
Current pattern is a drop-down.  What happens when more than 5 actions in the drop-down?
Rob Armes had an example from Fees & Payments. 
Discuss in a Design Crit.

**Comment by adamsilver** [comment]
![image](https://user-images.githubusercontent.com/37163/47437716-0b0e6780-d7a1-11e8-8739-cedfc212dcb1.png)

@trevorsaint put this together last week.

**Comment by adamsilver** [comment]
- check grey contrast
- perhaps a border to connect
- think about grouping/hierarchy for when there's a LOT of buttons
(speak more to Chris)

**Comment by adamsilver** [comment]
Improved the grey contrast

**Comment by adamsilver** [comment]
Here's the component with some guidance added:
http://hmcts-design-system.herokuapp.com/components/menu
