### ISSUE TITLE
Rich text editor

### ISSUE THREAD

**Issue by adamsilver** [hmcts/design-system-backlog#54]
![image](https://user-images.githubusercontent.com/37163/52638553-1e694e00-2eca-11e9-9411-e6bbaeeb302f.png)

Going to abstract rich text editor code in JUI.

**Comment by adamsilver** [comment]
In production.

**Comment by stevenwise-hmcts** [comment]
Suggest removing underline style. Underline isn't a GDS style. When viewed by citizens underlined text could be interpreted as links.

**Comment by stevenwise-hmcts** [comment]
Italic isn't a GDS style. Suggest removing this options for content intended to be displayed to citizens

**Comment by stevenwise-hmcts** [comment]
Consider adding a sub-heading style. Judges might use bold to create sub-headings which wouldn't be optimal for an accessibility perspective.
