### ISSUE TITLE
Add another

### ISSUE THREAD

**Issue by adamsilver** [hmcts/design-system-backlog#7]
- RPL: https://reform-pattern-library.herokuapp.com/components/add-another

There is no component for this in the GOV.UK Design System. We'll create an improved robust version of what's currently in the RPL.

I'd like to review the name of this component.

And we also need guidance as to when to use it.

**Comment by blowfishsoup** [comment]
Could we use stylised buttons instead maybe? 
![add another](https://user-images.githubusercontent.com/6122620/43568914-d9185916-962d-11e8-8c96-369b6b0f7322.png)

**Comment by adamsilver** [comment]
Done
